name = "leanathon"
version = "0.1.0"
defaultTargets = ["leanathon"]

[[lean_lib]]
name = "Leanathon"

[[lean_exe]]
name = "leanathon"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"